// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caltsztxawaulrhzovbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhbHRzenR4YXdhdWxyaHpvdmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzI1NDIsImV4cCI6MjA2NzY0ODU0Mn0.NYHStggb7hN8Ry69u95mdbULiKbnjvC6FoIOzB_mOxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});